version: "3"

services:
  client:
    build: ./client
    # ports:
    #   - "8080:8080"
    volumes:
      - ./client:/workspace:cached
      - /workspace/node_modules
    # command: |
    #   /bin/sh -c
    # "npm install"
    # "while sleep 1000; do :; done"
    # working_dir: /workspace
    tty: true

  server:
    build: ./server
    # ports:
    #   - "3000:3000"
    volumes:
      - ./server:/workspace:cached
      - /workspace/node_modules
    # command: /bin/sh -c "npm install"
    # "while sleep 1000; do :; done"
    # working_dir: /workspace
    tty: true
